language: elixir

otp_release:
  - 18.0
  - 19.3
  - 20.0

elixir:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6

matrix:
  exclude:
    - otp_release: 17.5
      elixir: 1.2
    - otp_release: 17.5
      elixir: 1.3
    - otp_release: 17.5
      elixir: 1.4
    - otp_release: 18.0
      elixir: 1.6
    - otp_release: 20.0
      elixir: 1.2
    - otp_release: 20.0
      elixir: 1.3

script:
  - mix local.hex --force
  - mix deps.get
  - mix ci_tests

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/0cb4f1057969bd327ed8
#    on_success: change
#    on_failure: always
#    on_start: false
