language: elixir
otp_release:
  - 17.5
  - 18.0
elixir:
  - 1.0.4
  - 1.0.5
env:
  - MIX_ENV=test
script:
  - mix local.hex --force
  - mix deps.get
  - mix compile --warnings-as-errors
  - mix dogma lib/
  - mix test
  - mix whiteBread.run
  - mix whiteBread.run --tags songs

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0cb4f1057969bd327ed8
    on_success: change
    on_failure: always
    on_start: false
